context:
    version: "0.8.0"
    python_min: "3.12"

package:
    name: hrms_utils
    version: ${{ version }}

source:
    path: ../src/
    use_gitignore: true

build:
    script: |
        export CARGO_HOME="$SRC_DIR/../.cache/rattler-cargo-home"
        export CARGO_TARGET_DIR="$SRC_DIR/../.cache/rattler-cargo-target"

        # 2. Enable sccache
        export RUSTC_WRAPPER="sccache"

        # 3. Build the package
        python -m build --wheel --outdir "$SRC_DIR/../dist/wheels" --no-isolation --skip-dependency-check
        mkdir -p "$RECIPE_DIR/../dist"
        cp "$SRC_DIR/../dist/wheels/"*.whl "$RECIPE_DIR/../dist/"
        python -m pip install "$SRC_DIR/../dist/wheels/"*.whl --no-deps --no-build-isolation -vv
    python:
        version_independent: true # Key setting for ABI3

requirements:
    ignore_run_exports:
        by_name:
            - python_abi
    build:
        - ${{ compiler('c') }}
        - cargo-bundle-licenses
        - rust >=1.91.0
        - rust-src >=1.91.0
        - rattler-build >=0.48.0
        - cmake
        - ninja
        - sccache
    host:
        - python
        - python-abi3 ==${{ python_min }} # Enables ABI3 compatibility
        - pip
        - python-build
        - maturin
        - cmake
        - ninja
    run:
        - python >=${{ python_min }}
        - polars >=1.35.2,<2
        - dataframely >=2.0.0,<3
        - rdkit >=2024.0.0
        - numpy >=1.20.0
        - parallel_rdkit >=0.3.0
        - scipy
        - pymzml >2.5.0
        - pandas
        - lxml
        - requests
        - aiohttp
        - pyarrow
        - python-calamine
        - openpyxl
        - xlsx2csv
        - xlsxwriter
        - connectorx
        - sqlalchemy

tests:
    - python:
          imports:
              - hrms_utils
          python_version: ["${{ python_min ~ '.*' }}", "3.13.*", "3.14.*"]

about:
    homepage: https://github.com/Nir-Cohen-2003/HRMS_utils
    # license: Apache 2.0
    license_file: LICENSE
    summary: fast usitlisites for HRMS data processing
    description: |
        polars based processing of spectral libraries, chromatogram and more. Rust based polars extension for core computational steps such as mass decomposition, spectra cleaning, spectral simailrity etc.
    repository: https://github.com/Nir-Cohen-2003/HRMS_utils
