[package]
name = "hrms_utils"
version = "0.7.0"
# edition = "2025"

[lib]
name = "hrms_utils"
crate-type = ["cdylib"]
path = "src/hrms_utils/spectral_search/rust_impl/entropy_lib.rs"

[dependencies]
pyo3 = { version = "0.25.0", features = ["extension-module"] }
pyo3-polars = { version = "0.24.0", features = ["derive"] }
polars = { version = "0.51.0", features = ["dtype-full"] }
rayon = "1.10.0"

[build-dependencies]
pyo3-build-config = "0.21.2"