[workspace]
authors = ["Nir <<>>"]
channels = ["conda-forge"]
name = "MS_utils_2"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
mces_bounds_full = "python -m  ms_utils.mces.bounds --bounds-test"
mces_bounds = "python -m  ms_utils.mces.bounds --bounds-test --no-mces"
mces_graph_construction = "python -m ms_utils.mces.lib --graph-benchmark"
mces_many = "python -m ms_utils.mces.mces"

[dependencies]
python = "3.12.*"
cuda-cudart = ">=12.9.79,<13"
networkx = ">=3.5,<4"
polars = ">=1.31.0,<2"
joblib = ">=1.5.1,<2"

[pypi-dependencies]
cuopt-cu12 = "==25.5.*"
rdkit = ">=2025.3.3, <2026"
pulp = "==3.2.1"
scipy = ">=1.16.1, <2"
rustworkx = ">=0.16.0, <0.17"
