[workspace]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
platforms = ["linux-64"]
preview = ["pixi-build"]

[dependencies]
python = "3.12.*"
ms_utils = {path="."}
[tasks]
start = "python -m ms_utils.__init__"

[package]
name = "ms_utils"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-python", version = "0.1.*" }
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]

[package.build-dependencies]
setuptools = ">=68.0.0"
# pixi-build-api-version = ">=0.1.0"


[package.host-dependencies]
setuptools = ">=68.0.0"
python = "3.12.*"
hatchling = "==1.26.3"


[package.run-dependencies]
polars = ">=1.31.0,<2"
rdkit = ">=2024.0.0"
