[workspace]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
platforms = ["linux-64"]
preview = ["pixi-build"]

[dependencies]
python = "3.12.*"
cython = ">=3.0.0"
setuptools = ">=68.0.0"
numpy = ">=1.20.0"
rdkit = ">=2024.0.0"
ms_utils = {path="."}
[pypi-dependencies]
build = "*"
[tasks]
start = "python -m ms_utils.__init__"
build-wheel = "python -m build"
build-all = "python -m build --wheel --sdist"


[package]
name = "ms_utils"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-python", version = "0.1.*" }
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
[package.build.configuration]
environment = { CFLAGS = "-I$PREFIX/include", LDFLAGS = "-L$PREFIX/lib -Wl,-rpath,$PREFIX/lib" }

[package.build-dependencies]
setuptools = ">=68.0.0"
cython = ">=3.0.0"
pip = "*"
numpy = ">=1.20.0"
rdkit = ">=2024.0.0"


[package.host-dependencies] 
setuptools = ">=68.0.0"
cython = ">=3.0.0"
# Virtual package that pulls in the correct C++ compiler for the target platform
cxx-compiler = "*"
# RDKit is needed for its C++ headers and libraries during compilation, for mces stuff
rdkit = ">=2024.0.0"
# Numpy is needed for its C headers
numpy = ">=1.20.0"
python = "3.12.*"

[package.run-dependencies]
rdkit = ">=2024.0.0"
polars = ">=1.32.0,<2"

