[project]
name = "ms-utils"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
# requires-python = ">=3.12"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = "3.12.*"
polars = ">=1.31.0,<2"
rdkit = ">=2024.0.0"

[pypi-dependencies]
cython = ">=3.1.2"
ipykernel = ">=6.29.5"
ms-entropy = "==1.3.4"
pyyaml = ">=6.0.2"
requests = ">=2.32.3"
seaborn = ">=0.13.2"
torch = ">=2.7.0"
joblib = ">=1.5.1,<2"
scipy = ">=1.16.0,<2"

[target.linux-64.pypi-dependencies]

[environments]
default = {features = [], solve-group = "default"}
mces = {features = ["mces"], solve-group = "mces"}
pyscreen = {features = ["pyscreen"], solve-group = "default"}
formula = {features = ["formula"], solve-group = "default"}
all = {features = ["pyscreen", "mces", "formula"], solve-group = "default"}

[feature.pyscreen.pypi-dependencies]
customtkinter = ">=5.2.2"

[feature.mces.dependencies]
librdkit-dev = ">=2024.0.0"
librdkit = ">=2024.0.0"
boost-cpp = "*"

[feature.mces.pypi-dependencies]
gurobipy = ">=12.0.1"
networkx = ">=3.4.2"
pulp = ">=3.2.1"
rustworkx = ">=0.16.0,<0.17"

[feature.mces.tasks]
mces_bounds_comparison_full = "python -m ms_utils.mces.bounds --bounds-validity-test"
mces_bounds_comparison = "python -m ms_utils.mces.bounds --bounds-validity-test --no-mces"
mces_bounds_strength_comparison = "python -m ms_utils.mces.bounds --bounds-strength-test"
mces_graph_construction = "python -m ms_utils.mces.graph_construction --graph-benchmark"
mces_dataset_splitting = "python -m ms_utils.mces.dataset_splitting"
mces_many = "python -m ms_utils.mces.mces"
mces_compile = "python -m ms_utils.mces.fast_mol_filter.setup build_ext --inplace"
mces_find_rdkit = "python -m ms_utils.mces.find_rdkit"

[feature.formula.pypi-dependencies]
lightgbm = ">=4.6.0"
molmass = {version = ">=2025.4.14", extras = ["all"]}
ms-entropy = "==1.3.4"
aiohttp = ">=3.11.18"

