[workspace]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
platforms = ["linux-64","win-64"]
preview = ["pixi-build"]

[dependencies]
python = "3.12.*"
pip = "*"
cython = ">=3.0.0"
setuptools = ">=68.0.0"
numpy = ">=1.20.0"
rdkit = ">=2024.0.0"
ms_utils = {path = "."}
[pypi-dependencies]
build = "*"

[tasks]
build-wheel = "python -m build"
build-all = "python -m build --wheel --sdist"


[package]
name = "ms_utils"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-python", version = "0.1.*" }
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
[package.build.configuration]
platforms = ["linux-64","win-64"]
# noarch = false
# script = "python -m pip install . -vv --no-deps --no-build-isolation"

[package.build-dependencies]
python = "3.12.*"
pip = "*"
numpy = ">=1.20.0"
setuptools = ">=68.0.0"
cython = ">=3.0.0"
cxx-compiler = "*"
pyarrow = ">=12.0.0" # might not be needed, but i do call it in the cython code

[package.host-dependencies] 
python = "3.12.*"
pip = "*"
numpy = ">=1.20.0"
setuptools = ">=68.0.0"
cython = ">=3.0.0"
cxx-compiler = "*"

[package.run-dependencies]
polars = ">=1.32.0,<2"
rdkit = ">=2024.0.0"
numpy = ">=1.20.0"
numba = ">=0.55.0"
ms_entropy = "==1.3.4"
scipy = ">=1.7.0"
requests = ">=2.25.0"
aiohttp = ">=3.8.1"
# for polars
pyarrow = ">=12.0.0"
pandas = ">=1.3.0"
openpyxl = "*"
xlsx2csv = "*"
xlsxwriter = "*"
connectorx = "*"
sqlalchemy = "*"
[environments]
default = {features = [], solve-group = "default"}
