[workspace]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
  "https://prefix.dev/nir-cohen",
  "conda-forge",
]
platforms = ["linux-64","win-64"]
preview = ["pixi-build"]
[package]
name = "hrms_utils"
version = "0.8.0"
license = "Apache-2.0"
license-file = "LICENSE"
authors = ["Nir Cohen"]
[dependencies]
hrms_utils = {path = "."}


[pypi-dependencies]
build = "*"

[tasks]

cibw-wheels = { cmd = "python -m cibuildwheel --output-dir dist dist/*.tar.gz", env = {CIBW_BUILD = " cp310-* cp311-* cp312-* cp313-* cp314-*", CIBW_SKIP = "*musllinux* *-win32", CIBW_ARCHS_WINDOWS = "AMD64", CIBW_PACKAGE = "."}, depends-on=["build-sdist"]}
build-sdist = {cmd="python -m build --sdist --outdir dist", depends-on = ["clean_dist"]}
build-wheel = "python -m build --wheel --outdir dist"
build-all = {cmd="python -m build --wheel --sdist --outdir dist",depends-on = ["clean_dist"]}
clean_dist = "rm -rf dist || true"

publish-testpypi = {cmd="twine upload --repository testpypi --skip-existing dist/*", depends-on = ["build-all"]}
publish-pypi = {cmd="twine upload --repository pypi --skip-existing dist/*", depends-on = ["build-all"]}

publish-prefix = {cmd="rattler-build upload prefix --channel nir-cohen"}
publish-anaconda = {cmd="rattler-build upload anaconda --owner Nir_Cohen --channel main"}

[target.win-64.tasks]
build-wheel = { cmd = "python -m build --wheel --no-isolation --outdir dist"}
build-all = { cmd = "python -m build --wheel --sdist --no-isolation --outdir dist"}

[environments]
default = {features = [], solve-group = "default"}
testing = {features = ["testing"], solve-group = "testing"}
experiments = {features = ["experiments"], solve-group = "experiments",no-default-feature = true}

[package.build]
backend = { name = "pixi-build-python", version = "*",channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]}
[package.build.config]
noarch = false
[workspace.build-variants]
python = ["3.12", "3.13","3.14"]
[package.build-dependencies]
python = "*"
pip = "*"
numpy = ">=1.20.0,<3.0"
hatchling = ">=1.13.2"
setuptools = ">=68.0.0"
maturin = ">=1.09.0"
rattler-build = ">=0.48.0"
rust = ">=1.91.0"
rust-src = ">=1.91.0"
compilers = "*"
cargo-bundle-licenses = "*"
[package.host-dependencies] 
python = "*"
pip = "*"
maturin = ">=1.09.0,<2.0"
[package.run-dependencies]
polars = ">=1.35.2,<2"
rdkit = ">=2024.0.0"
numpy = ">=1.20.0"
scipy = "*"
pymzml = ">2.5.0"
pandas = "*"
lxml = "*"
requests = "*"
aiohttp = "*"
# for polars
pyarrow = "*"
python-calamine = "*"
openpyxl = "*"
xlsx2csv = "*"
xlsxwriter = "*"
connectorx = "*"
sqlalchemy = "*"

[feature.testing.tasks]
check_all = "pyrefly check ./src/hrms_utils"
check_nist_mspec = "pyrefly check ./src/hrms_utils/formats/nist_mspec.py"

test = {cmd="echo 'All tests passed!'", depends-on = [
    "test_core_utils",
    "test_nist_mspec",
    "test_chromatogram",
    # "test_mol",
    "test_info_score",
    "test_isotopic_pattern",

  ]}
test_core_utils = "pytest tests/hrms_core"
test_nist_mspec = {cmd="python tests/formats/test_nist_mspec.py",env={ POLARS_VERBOSE= "1" }}
test_chromatogram = {cmd="python tests/formats/chromatogram.py",env ={ POLARS_VERBOSE= "0" }}
test_mol = "python tests/rdkit/mol.py"
test_info_score = "python tests/spectral/test_spectral_information.py"
test_isotopic_pattern = "pytest tests/hrms_core/test_isotopic_pattern.py"
test_mzml = "pytest tests/hrms_core/test_mzml_io.py"

convert_msp = "python scripts/convert_msp.py"

[feature.testing.dependencies]
hrms_utils = {path = "."}
polars = ">=1.35.2,<2"
rdkit = ">=2024.0.0"
numpy = ">=1.20.0,<2.3"
numba = ">=0.61.0"
pytest = ">=8.4.2,<9"
optuna = "*"
scipy = "*"
requests = "*"
aiohttp = "*"
pyarrow = ">=12.0.0"
pandas = "*"
python-calamine = "*"
openpyxl = "*"
xlsx2csv = "*"
xlsxwriter = "*"
connectorx = "*"
sqlalchemy = "*"
ipykernel = "*"
plotly = ">=6.3.0,<7"
nbformat = ">=5.10.4,<6"
marimo ="*"
ruff = "*"
[feature.testing.pypi-dependencies]
kaleido = ">=1.1.0, <2"

# [feature.experiments.target.linux-64.system-requirements]
[feature.experiments.target.linux-64.dependencies]
hrms_utils = {path = "."}
polars = ">=1.35.2,<2"
rdkit = ">=2024.0.0"
numpy = "*"
optuna = "*"
nvmolkit = "*"
pyzmq = "*"
pytorch-gpu = "*"
# cuda-version = "12.6.*"
marimo ="*"

[feature.experiments.system-requirements]
cuda = "12.0"