[workspace]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
platforms = ["linux-64"]
preview = ["pixi-build"]

[dependencies]
python = "3.12.*"
ms_utils = {path="."}
[pypi-dependencies]
build = "*"
[tasks]
start = "python -m ms_utils.__init__"
build-wheel = "python -m build"
build-all = "python -m build --wheel --sdist"


[package]
name = "ms_utils"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-python", version = "0.1.*" }
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]

[package.build-dependencies]
setuptools = ">=68.0.0"


[package.host-dependencies] 
setuptools = ">=68.0.0"


# [package.run-dependencies]
# polars = ">=1.32.0,<2"
# rdkit = ">=2024.0.0"

