[project]
name = "ms-utils"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.18",
    "customtkinter>=5.2.2",
    "gurobipy>=12.0.1",
    "lightgbm>=4.6.0",
    "molmass[all]>=2025.4.14",
    "ms-entropy>=1.3.5",
    "msbuddy>=0.3.12",
    "networkx>=3.4.2",
    "polars[all]==1.30.0",
    "pulp>=3.1.1",
    "pyyaml>=6.0.2",
    "rdkit>=2024.9.6",
    "requests>=2.32.3",
    "torch>=2.7.0",
]
