[project]
name = "hrms_utils"
# version = "0.8.0"
license = "Apache-2.0"
license-files = ["LICENSE"]
requires-python = ">=3.12"
dependencies = [
    "polars>=1.35.2,<2",
    "rdkit>=2024.0.0",
    "numpy>=1.20.0",
    "numba>=0.61.0",
    "requests",
    "aiohttp",
    "scipy",
    # for polars
    "pyarrow>=12.0.0",
    "pandas",
    "openpyxl",
    "python-calamine",
    "xlsx2csv",
    "xlsxwriter",
    "connectorx",
    "sqlalchemy",
]
dynamic = ["version"]
[build-system]
requires = ["setuptools>=61.0", "setuptools-rust>=1.5.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
# [build-system]
# requires = ["maturin>=1.09,<2"]
# build-backend = "maturin"
# compatibility = "abi3-py312"
# [tool.maturin]
# features = ["pyo3/extension-module"]
# # Point to the existing Rust project
# manifest-path = "Cargo.toml"
# # Compile the extension as hrms_utils._internal
# module-name = "hrms_utils._internal"
# # Tell maturin where the main python source is (so it bundles hrms_utils)
# python-source = "src"

[tool.ty.src] #thsi project uses pyrefly, but mrimo introduces the ty type checker, which we disable
exclude = ["src", "scripts", "tests","experiments"]
