[project]
name = "ms-utils"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.18",
    "gurobipy>=12.0.1",
    "lightgbm>=4.6.0",
    "msbuddy>=0.3.12",
    "networkx>=3.4.2",
    "polars>=1.27.1",
    "pulp>=3.1.1",
    "rdkit>=2024.9.6",
    "requests>=2.32.3",
]
