[project]
name = "ms_utils"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "polars>=1.32.0,<2",
    "rdkit>=2024.0.0"
]
[build-system]
requires = ["setuptools"]#, "setuptools-scm"
build-backend = "setuptools.build_meta"


