context:
  version: "0.1.0"

package:
  name: spectral_similarity
  version: ${{ version }}

source:
  path: ..
  use_gitignore: true

build:
  script: bash recipe/build.sh

requirements:
  build:
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - maturin
    - pip
  host:
    - python
  run:
    - python

tests:
  - script:
      - python -c "import hrms_utils"

about:
  homepage: https://github.com/Nir-Cohen-2003/HRMS_utils
  license: MIT
