[workspace]
authors = ["Nir <<>>"]
channels = ["conda-forge"]
name = "mces"
platforms = ["linux-64"]
version = "0.1.0"
preview = ["pixi-build"]
[tasks]

[package]
name = "mces"
version = "0.1.0"
authors = ["Nir <>"]

[package.build]
backend = { name = "pixi-build-cmake", version = "0.1.*" }
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
[package.build.configuration]
# This will run cmake, build and install the package
cmake_args = ["-S", ".", "-B", "build", "-DCMAKE_INSTALL_PREFIX=$PREFIX", "-DCMAKE_BUILD_TYPE=Release"]
build_args = ["--build", "build"]
install_args = ["--install", "build"]

[package.build-dependencies]
cmake = "*"
ninja = "*"

[package.host-dependencies]
# Virtual package that pulls in the correct C++ compiler for the target platform
cxx-compiler = "*"
# RDKit is needed for its C++ headers and libraries during compilation
rdkit = ">=2024.0.0"
librdkit = ">=2024.0.0"
# Add boost-cpp for the C++ headers and libraries
boost-cpp = "*"
eigen = "*"
# # The munkres library for the Hungarian algorithm
munkres = "*"

[package.run-dependencies]
# The runtime dependencies of the package
rdkit = ">=2024.0.0"
librdkit = ">=2024.0.0"
munkres = "*"
