context:
  version: "0.1.0"
  python_min: "3.9"

package:
  name: spectral_similarity
  version: ${{ version }}

source:
  path: ..
  use_gitignore: true

build:
  script: pip install . -v --no-deps
  python:
    version_independent: true

requirements:
  build:
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python      ${{ python_min }}.*
    - python-abi3 ${{ python_min }}.*
    - maturin
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - script:
      - pwd
      - ls -la
      # - python $SRC_DIR/tests/test.py

about:
  homepage: https://github.com/Nir-Cohen-2003/HRMS_utils
  license: MIT
