[project]
name = "hrms_utils"
license = "Apache-2.0"
license-files = ["LICENSE"]
requires-python = ">=3.12"
dependencies = [
    "polars>=1.35.2,<2",
    "rdkit>=2024.0.0",
    "numpy>=1.20.0",
    "numba>=0.61.0",
    "parallel_rdkit",
    "requests",
    "aiohttp",
    "scipy",
    # for polars
    "pyarrow>=12.0.0",
    "pandas",
    "openpyxl",
    "python-calamine",
    "xlsx2csv",
    "xlsxwriter",
    "connectorx",
    "sqlalchemy",
]
dynamic = ["version"]

[project.scripts]
build-spectral-library = "hrms_utils.cli.process_spectral_library:main"

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
module-name = "hrms_utils._internal"
python-source = "."
features = ["pyo3/abi3-py312"]
bindings = "pyo3"
exclude = ["scripts/**", "tests/**","experiments/**","docs/**","results/**","ideas/**"]

[tool.ty.src] #this project uses pyrefly, but mrimo introduces the ty type checker, which we disable
exclude = ["src", "scripts", "tests","experiments"]
