name: Build Package

on:
  push:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install pixi
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          curl -fsSL https://pixi.sh/install.sh | bash
          echo "$HOME/.pixi/bin" >> $GITHUB_PATH
        elif [ "$RUNNER_OS" == "Windows" ]; then
          irm https://pixi.sh/install.ps1 | iex
          echo "$APPDATA\pixi\bin" >> $GITHUB_PATH
        fi
      shell: bash

    - name: Build with pixi
      run: pixi run build-all

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{ matrix.platform }}
        path: dist/