name: Build Package

on:
  push:
    branches: [ main ]
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  wheels:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install pixi (Linux)
        if: runner.os == 'Linux'
        run: |
          curl -fsSL https://pixi.sh/install.sh | bash
          echo "$HOME/.pixi/bin" >> $GITHUB_PATH

      - name: Install pixi (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
            irm https://pixi.sh/install.ps1 | iex
            echo "$HOME\.pixi\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Show pixi version
        run: pixi --version

      - name: Build wheels with cibuildwheel
        env:
          CIBW_BUILD: "cp312-*"
          CIBW_SKIP: "pp* *musllinux*"
          CIBW_BEFORE_BUILD: "pip install cython"
          CIBW_TEST_COMMAND: "python -c 'import hrms_utils'"
        run: pixi run cibw-wheels

      - name: Build sdist (only on Linux)
        if: runner.os == 'Linux'
        run: pixi run sdist

      - name: List dist
        run: ls -1 dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          path: dist/

  publish-testpypi:
    needs: wheels
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: dist-*
          merge-multiple: true

      - name: List collected files
        run: ls -l dist

      - name: Install twine (use runner Python)
        run: python -m pip install -U twine

      - name: Verify distributions
        run: twine check dist/*

      - name: Upload to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: twine upload --repository testpypi dist/*